version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-static/portal/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-static/portal/rabbitmq/log/:/var/log/rabbitmq
  producer:
    build: .
    user: "1000"
    container_name: producer
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - ./producer:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
  consumer:
    build: .
    user: "1000"
    container_name: consumer
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - ./consumer:/app/src
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
